/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { PetSnapshotRequest, PetSnapshotValue } from 'dsh-desktop-pet/client'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$706574537461747573 {
    snapshot: (request: PetSnapshotRequest) => Promise<RemoteResult<PetSnapshotValue>>
  }
  interface TypertRemoteMap {
    'petStatus/snapshot': (request: PetSnapshotRequest) => Promise<RemoteResult<PetSnapshotValue>>
  }
  interface TypertRemoteNamespaceMap {
    'petStatus': TypertRemoteNamespace$706574537461747573
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
