/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_pet_status_petStatus_snapshot_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_pet_status_petStatus_snapshot_result$schema = z.object({
  'phase': z.union([z.literal("error"), z.literal("idle"), z.literal("thinking"), z.literal("working")]).readonly(),
  'tool': z.union([z.literal(null), z.string()]).readonly(),
  'elapsed': z.number().readonly(),
  'error': z.union([z.literal(null), z.string()]).readonly(),
  'balance': z.union([z.literal(null), z.number()]).readonly(),
  'balanceCurrency': z.union([z.literal(null), z.string()]).readonly(),
  'balancePending': z.boolean().readonly(),
  'balanceError': z.union([z.literal(null), z.string()]).readonly(),
  'balanceScale': z.number().readonly(),
})

export const TYPERT = {
  package: 'dsh-desktop-pet',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-desktop-pet#petStatus/snapshot',
      service: 'petStatus',
      namespace: 'petStatus',
      method: 'snapshot',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-desktop-pet/client#PetSnapshotRequest',
            schema: _deepseek_ai_dsh_pet_status_petStatus_snapshot_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-desktop-pet/client#PetSnapshotValue',
        schema: _deepseek_ai_dsh_pet_status_petStatus_snapshot_result$schema,
      },
      sourceLocation: {"file":"src/index.ts","line":131,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "description": "Live pet-status service: folds agent events per session and serves one snapshot plus the latest cached DeepSeek balance over the Remote API.",
        "summary": "Live pet-status service: folds agent events per session and serves one snapshot plus the latest cached DeepSeek balance over the Remote API.",
        "tags": [],
        "jsDoc": "/**\n * Live pet-status service: folds agent events per session and serves one\n * snapshot plus the latest cached DeepSeek balance over the Remote API.\n */",
        "key": "petStatus",
        "exportName": "PetStatusService",
        "members": [
          {
            "kind": "method",
            "name": "snapshot",
            "signature": "@Remote('snapshot') snapshot(request: PetSnapshotRequest): PetSnapshotValue",
            "summary": "Read one pet snapshot, calibrating the fold against the live agent and triggering a cached balance refresh when the cache is stale.",
            "jsDoc": "/**\n * Read one pet snapshot, calibrating the fold against the live agent and\n * triggering a cached balance refresh when the cache is stale. The Remote\n * face wraps the business value in the standard result envelope.\n * @param request - the session whose agent the pet reflects.\n * @returns the snapshot value.\n */"
          }
        ],
        "types": [
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "PetPhase",
            "declaration": "export type PetPhase = 'idle' | 'thinking' | 'working' | 'error';"
          },
          {
            "name": "PetSnapshotRequest",
            "declaration": "export interface PetSnapshotRequest {\n    readonly sessionId: SessionId;\n}"
          },
          {
            "name": "PetSnapshotValue",
            "declaration": "export interface PetSnapshotValue {\n    readonly phase: PetPhase;\n    readonly tool: string | null;\n    readonly elapsed: number;\n    readonly error: string | null;\n    readonly balance: number | null;\n    readonly balanceCurrency: string | null;\n    readonly balancePending: boolean;\n    readonly balanceError: string | null;\n    readonly balanceScale: number;\n}"
          },
          {
            "name": "SessionId",
            "declaration": "export type SessionId = Branded<'SessionId'>;"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
